/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsIdRouteImport } from './routes/forms.$id'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as ChatRidRouteImport } from './routes/chat.$rid'
import { Route as DashboardEditIdRouteImport } from './routes/dashboard.edit.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdRoute = FormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ChatRidRoute = ChatRidRouteImport.update({
  id: '/chat/$rid',
  path: '/chat/$rid',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditIdRoute = DashboardEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/chat/$rid': typeof ChatRidRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/forms/$id': typeof FormsIdRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/chat/$rid': typeof ChatRidRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/forms/$id': typeof FormsIdRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/chat/$rid': typeof ChatRidRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/forms/$id': typeof FormsIdRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/chat/$rid'
    | '/dashboard/new'
    | '/forms/$id'
    | '/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/chat/$rid'
    | '/dashboard/new'
    | '/forms/$id'
    | '/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/chat/$rid'
    | '/dashboard/new'
    | '/forms/$id'
    | '/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ChatRidRoute: typeof ChatRidRoute
  FormsIdRoute: typeof FormsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id': {
      id: '/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof FormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/chat/$rid': {
      id: '/chat/$rid'
      path: '/chat/$rid'
      fullPath: '/chat/$rid'
      preLoaderRoute: typeof ChatRidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/edit/$id': {
      id: '/dashboard/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof DashboardEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardEditIdRoute: typeof DashboardEditIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNewRoute: DashboardNewRoute,
  DashboardEditIdRoute: DashboardEditIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ChatRidRoute: ChatRidRoute,
  FormsIdRoute: FormsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
